site_name: Dokumentacja
site_url: https://github.com/kubansa-allegro/doc/

nav:
  - Home: index.md
  - Zadania: zadania.md
  - Instrukcja analityka: instrukcja_analityka.md
  - Help:
    - Help Mkdocs: https://squidfunk.github.io/mkdocs-material/reference/


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/smiling_face.ico
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.path
    - toc.follow
    - navigation.expand
  language: pl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      logo: assets/logo.png
      favicon: assets/smiling_face.ico

plugins:
  - tags
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kubansa-allegro
    - icon: fontawesome/brands/slack
      link: https://allegro.slack.com/archives/D03S5RWAPHP
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adam-kubanski-2bb020a8/

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - tables

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.tasklist:
      custom_checkbox: true


markdown: kramdown

kramdown:
  toc_levels: 1..2



copyright: |
  &copy; 2024 <a href="https://github.com/kubansa-allegro"  target="_blank" rel="noopener">Adam Kubanski</a>